name: Verificar Archivos

on:
  push:
    branches:
      - main

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Validar archivos de JavaScript
        run: |
          for i in {1..10}; do
            if [ ! -f "ejercicios-js/ejercicio${i}.js" ]; then
              echo "ERROR: ejercicios-js/ejercicio${i}.js no encontrado."
              exit 1
            fi
          done
          echo "Todos los archivos de JavaScript existen."

      - name: Validar archivos de Python
        run: |
          for i in {1..10}; do
            if [ ! -f "ejercicios-py/ejercicio${i}.py" ]; then
              echo "ERROR: ejercicios-py/ejercicio${i}.py no encontrado."
              exit 1
            fi
          done
          echo "Todos los archivos de Python existen."